name: Deploy Contacts Web UI and API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  AZURE_WEBAPI_PACKAGE_PATH: '.'
  DOTNET_CORE_VERSION: 7.0.x

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Install dependencies
      run: dotnet restore ./src/Contacts.sln
    - name: Build API
      run: dotnet build ./src/Contacts.Api/Contacts.Api.csproj --configuration Release --no-restore
    - name: Build Web
      run: dotnet build ./src/Contacts.WebUi/Contacts.WebUi.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test ./src/Contacts.sln --no-restore --verbosity normal
    - name: Publish WebUI
      run: dotnet publish ./src/Contacts.WebUi/Contacts.WebUi.csproj  -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}' 
    - name: Publish Web API
      run: dotnet publish ./src/Contacts.Api/Contacts.Api.csproj  -c Release -o '${{ env.AZURE_WEBAPI_PACKAGE_PATH }}'
    - name: Publish Web UI Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    - name: Publish Web API Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: webapi
        path: ${{ env.AZURE_WEBAPI_PACKAGE_PATH }}
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job - Web UI
        uses: actions/download-artifact@v3
        with:
          name: webapp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      - name: Deploy to Azure Function App
        uses: Azure/webapps-deploy@v2
        with:
          app-name: cwjg-contacts-noauth-web
          publish-profile: ${{ secrets.WEB_UI_NOAUTH_PUBLISH_PROFILE  }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
      - name: Download artifact from build job - Web API
        uses: actions/download-artifact@v3
        with:
          name: webapi
          path: ${{ env.AZURE_WEBAPI_PACKAGE_PATH }}
      - name: Azure WebApp - Web API
        uses: Azure/webapps-deploy@v2
        with:
          app-name: cwjg-contacts-noauth-api
          publish-profile: ${{ secrets.WEB_API_NOAUTH_PUBLISH_PROFILE  }}
          package: '${{ env.AZURE_WEBAPI_PACKAGE_PATH }}'
    
